top_srcdir   = /home/centos/Desktop/xamin/httpd-2.2.22
top_builddir = /home/centos/Desktop/xamin/httpd-2.2.22
srcdir       = /home/centos/Desktop/xamin/httpd-2.2.22/modules/filters
builddir     = /home/centos/Desktop/xamin/httpd-2.2.22/modules/filters
VPATH        = /home/centos/Desktop/xamin/httpd-2.2.22/modules/filters

include $(top_srcdir)/build/special.mk

