top_srcdir   = /home/centos/Desktop/xamin/httpd-2.2.22
top_builddir = /home/centos/Desktop/xamin/httpd-2.2.22
srcdir       = /home/centos/Desktop/xamin/httpd-2.2.22/modules/aaa
builddir     = /home/centos/Desktop/xamin/httpd-2.2.22/modules/aaa
VPATH        = /home/centos/Desktop/xamin/httpd-2.2.22/modules/aaa

include $(top_srcdir)/build/special.mk

