top_srcdir   = /home/centos/Desktop/xamin/httpd-2.2.22
top_builddir = /home/centos/Desktop/xamin/httpd-2.2.22
srcdir       = /home/centos/Desktop/xamin/httpd-2.2.22/modules/cache
builddir     = /home/centos/Desktop/xamin/httpd-2.2.22/modules/cache
VPATH        = /home/centos/Desktop/xamin/httpd-2.2.22/modules/cache

include $(top_srcdir)/build/special.mk

