top_srcdir   = /home/centos/Desktop/xamin/httpd-2.2.22
top_builddir = /home/centos/Desktop/xamin/httpd-2.2.22
srcdir       = /home/centos/Desktop/xamin/httpd-2.2.22/server/mpm
builddir     = /home/centos/Desktop/xamin/httpd-2.2.22/server/mpm
VPATH        = /home/centos/Desktop/xamin/httpd-2.2.22/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
